= Poradnik testera DogeChat
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:toc2:
:toc-title: Spis treści
:max-width: 100%


Tłumaczenie:

* Krzysztof Korościk <soltys@szluug.org>, 2009-2015


[[purpose]]
== Cel

Wielu wdzięcznych użytkowników pyta nas jak mogą pomóc w rozwoju DogeChat.
Najłatwiejszym (a zarazem najtrudniejszym) sposobem jest testowanie!

Testowanie jest bardzo ważną częścią rozwoju oprogramowania i nie powinno być
niedoceniane. Kiedy nowe funkcje są implementowane, powinny zostać przetestowane,
ale dla wielu z nich jest za dużo możliwości użycia lub nie są łatwe do
za symulowania dlatego programiści nie są wstanie sprawdzić ich wszystkich.

Na przykład: Powszechnie znana wtyczka od kodowania została wprowadzona w
DogeChat 0.2.2: żaden z nas (programistów, współpracowników, testerów) nie
używał kanałów ze znakami narodowymi w nazwach, kiedy wersja 0.2.2 została
wypuszczona zostaliśmy zalani użytkownikami z Rosji obwiniającymi nas.
Gdy będziemy mieli więcej testerów taka sytuacja nie powinna się już zdarzyć
w przyszłości.

Testowanie stabilnej wersji DogeChat jest bezcelowe, ponieważ programiści są
zajęci cały czas implementowaniem nowych rzeczy (oraz poprawianiem błędów).


[[prepare_system]]
== Przygotuj swój system

Bardzo nam pomoże, jeśli włączysz linuksowe pliki 'core': jeśli DogeChat zawiesi
się Linux zapisze plik zwany 'core'. Plik ten zawiera użyteczne informacje
pozwalające dokładnie zlokalizować błąd w DogeChat.

Jeśli korzystasz z powłoki 'bash', dodaj następującą linijkę do `~/.bashrc`:

----
ulimit -c unlimited
----


[[download]]
== Pobieranie wersji rozwojowej

Świeży kod (z najnowszymi błędami i funkcjami) przechowywany jest w repozytorium GIT.

Możesz się zdecydować na własnoręczne zbudowanie (zalecana metoda):

* wersja z GIT może być zbudowana i zainstalowana równolegle z wersją stabilną,
* nie potrzebujesz uprawnień administratora, oraz nie musisz poświęcać stabilnej
  wersji DogeChat.

[[get_sources]]
=== Pobierz i zbuduj źródła

Najpierw stwórz katalog, na przykład 'dogechat-git':

----
$ mkdir ~/dogechat-git
$ cd ~/dogechat-git
----

Jeśli masz zainstalowanego gita, po prostu sklonuj repozytorium (zalecana
metoda):

----
$ git clone https://github.com/dogechat/dogechat.git
$ cd dogechat
----

UWAGA: Później możesz wykonać w tym katalogu "`git pull`", aby pobrać najnowsze
poprawki.

Oczywiście możesz pobrać paczkę oznaczoną jako 'devel':

----
$ wget https://dogechat.org/files/src/dogechat-devel.tar.bz2
$ tar xvjf dogechat-devel.tar.bz2
$ cd dogechat-devel
----

Do zbudowania źródeł zaleca się cmake:

----
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/dogechat-git -DDOGECHAT_HOME=~/.dogechat-dev -DCMAKE_BUILD_TYPE=Debug
$ make
$ make install
----

Jeśli nie posiadasz cmake, nadal jest możliwe użycie autotools:

----
$ ./autogen.sh
$ ./configure --prefix=$HOME/dogechat-git DOGECHAT_HOME=~/.dogechat-dev
$ make
$ make install
----

[[install_binary_package]]
=== Instalowanie pakietów binarnych

W zależności od dystrybucji Linuksa:

* Debian: https://dogechat.org/download/debian
* Gentoo: https://dogechat.org/download
* ArchLinux: PKGBUILD z http://aur.archlinux.org/
* inne: nie mamy pojęcia! Eheh.


[[run]]
== Uruchomienie DogeChat

Zaleca się uruchomianie DogeChat z innym katalogiem (różnym od wersji stabilnej),
za pomocą opcji `--dir`.

Komenda to:

----
$ ~/dogechat-git/bin/dogechat
----

Jeśli nadal nie śpisz powinieneś ujrzeć znajomy interfejs i chwalić się
z posiadania najnowszej możliwej wersji DogeChat. ;)

Teraz jeśli zaobserwujesz dziwne zachowanie (może sprawiać problemy, ulec awarii
lub zagotować Twoje piwo) nie wahaj się wejść na kanał `#dogechat` na serwerze
`chat.freenode.net` i nam o tym opowiedzieć.

Jeśli wszystko będzie w porządku - też nam o tym powiedz, potrzebujemy Twojej opinii!
