= DOGECHAT(1)
:doctype: manpage

== 名前

dogechat - 拡張可能なチャットクライアント

== 書式

[verse]
'dogechat' [-a|--no-connect] [-d|--dir <path>] [-p|--no-plugin] [-r|--run-command <command>] [-s|--no-script] [--upgrade] [plugin:option...]
'dogechat' [-c|--colors]
'dogechat' [-h|--help]
'dogechat' [-l|--license]
'dogechat' [-v|--version]

== 説明

DogeChat (Doge Enhanced Environment for Chat) はフリーのチャットクライアントです。
高速で軽量、多くのオペレーティングシステムで動くように設計されています。
スクリプトを使って高度にカスタマイズと拡張可能です。

== オプション

include::cmdline_options.ja.asciidoc[]

== プラグインオプション

プラグインオプションに関する完全な文書は
https://dogechat.org/doc[DogeChat ユーザーガイド] のプラグインリファレンスを参照してください。

irc プラグインでは以下の様な URL で一時的なサーバに接続することができます:

    irc[6][s]://[[nickname][:password]@]server[:port][/#channel1[,#channel2...]]

"mynick" というニックネームで DogeChat IRC チャンネルサポートに参加するには:

    irc://mynick@chat.freenode.net/#dogechat

IPv6 アドレスの後にポートを指定するには IPv6
アドレスを括弧に入れてください、例えば:

    irc://mynick@[2001:db8:0:85a3::ac1f:8001]:6668/#test

== ファイル

$HOME/.dogechat/dogechat.conf::
    DogeChat の主設定ファイル

$HOME/.dogechat/plugins.conf::
    プラグイン設定ファイル

$HOME/.dogechat/sec.conf::
    保護されたデータを含む設定ファイル

$HOME/.dogechat/alias.conf::
    'alias' プラグイン用の設定ファイル

$HOME/.dogechat/aspell.conf::
    'aspell' プラグイン用の設定ファイル

$HOME/.dogechat/charset.conf::
    'charset' プラグイン用の設定ファイル

$HOME/.dogechat/exec.conf::
    'exec' プラグイン用の設定ファイル

$HOME/.dogechat/irc.conf::
    'irc' プラグイン用の設定ファイル

$HOME/.dogechat/logger.conf::
    'logger' プラグイン用の設定ファイル

$HOME/.dogechat/relay.conf::
    'relay' プラグイン用の設定ファイル

$HOME/.dogechat/script.conf::
    'script' プラグイン用の設定ファイル

$HOME/.dogechat/trigger.conf::
    'trigger' プラグイン用の設定ファイル

$HOME/.dogechat/xfer.conf::
    'xfer' プラグイン用の設定ファイル

$HOME/.dogechat/dogechat.log::
    DogeChat ログファイル

== 著者

この manpage を書いたのは Sébastien Helleu <flashcode@flashtux.org> さんです。

翻訳したのは Ryuunosuke Ayanokouzi <i38w7i3@yahoo.co.jp> さんです。

== 著作権

DogeChat は Sébastien Helleu さんと貢献者によって作成されています
(完全なリストは AUTHORS.asciidoc ファイルを参照してください)。

著作権 (C) 2003-{sys:date "+%Y"} Sébastien Helleu <flashcode@flashtux.org>

DogeChat はフリーソフトウェアです。あなたはこれを、フリーソフトウェア財団によって発行された
GNU 一般公衆利用許諾契約書 (バージョン2か、希望によってはそれ以降のバージョンのうちどれか)
の定める条件の下で再頒布または改変することができます。

より詳しい情報は COPYING ファイルを読んでください。

Web: <https://dogechat.org/>

== サポート / バグ報告

手助けを受けたりバグを報告するには: <https://dogechat.org/dev/support>
